trycf/config/routes.rb
Trycf::Application.routes.draw do
  resources :primes

end

trycf/app/models/prime.rb
class Prime < ActiveRecord::Base
  attr_accessible :is_prime, :num

  def prime?
    2.upto(num.to_i - 1) do |i|
      return false if (num % i) == 0
    end

    return true
  end
end

trycf/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

trycf/app/controllers/primes_controller.rb
class PrimesController < ApplicationController
  # GET /primes
  # GET /primes.json
  def index
    @primes = Prime.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @primes }
    end
  end

  # GET /primes/1
  # GET /primes/1.json
  def show
    @prime = Prime.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @prime }
    end
  end

  # GET /primes/new
  # GET /primes/new.json
  def new
    @prime = Prime.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @prime }
    end
  end

  # GET /primes/1/edit
  def edit
    @prime = Prime.find(params[:id])
  end

  # POST /primes
  # POST /primes.json
  def create
    @prime = Prime.new(params[:prime])
    @prime.is_prime = true if @prime.prime?

    respond_to do |format|
      if @prime.save
        if @prime.is_prime
          msg = "#{@prime.num} is prime!!"
        else
          msg = "#{@prime.num} is not prime!!"
        end

        format.html { redirect_to @prime, notice: msg }
        format.json { render json: @prime, status: :created, location: @prime }
      else
        format.html { render action: "new" }
        format.json { render json: @prime.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /primes/1
  # PUT /primes/1.json
  def update
    @prime = Prime.find(params[:id])

    respond_to do |format|
      if @prime.update_attributes(params[:prime])
        format.html { redirect_to @prime, notice: 'Prime was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @prime.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /primes/1
  # DELETE /primes/1.json
  def destroy
    @prime = Prime.find(params[:id])
    @prime.destroy

    respond_to do |format|
      format.html { redirect_to primes_url }
      format.json { head :no_content }
    end
  end
end

trycf/app/helpers/application_helper.rb
module ApplicationHelper
end

trycf/app/helpers/primes_helper.rb
module PrimesHelper
end

trycf/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Trycf</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

trycf/app/views/primes/_form.html.erb
<%= form_for(@prime) do |f| %>
  <% if @prime.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@prime.errors.count, "error") %> prohibited this prime from being saved:</h2>

      <ul>
      <% @prime.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :num %><br />
    <%= f.number_field :num %>
  </div>
  <div class="field">
    <%= f.label :is_prime %><br />
    <%= f.check_box :is_prime %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

trycf/app/views/primes/edit.html.erb
<h1>Editing prime</h1>

<%= render 'form' %>

<%= link_to 'Show', @prime %> |
<%= link_to 'Back', primes_path %>

trycf/app/views/primes/index.html.erb
<h1>Listing primes</h1>

<table>
  <tr>
    <th>Num</th>
    <th>Is prime</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @primes.each do |prime| %>
  <tr>
    <td><%= prime.num %></td>
    <td><%= prime.is_prime %></td>
    <td><%= link_to 'Show', prime %></td>
    <td><%= link_to 'Edit', edit_prime_path(prime) %></td>
    <td><%= link_to 'Destroy', prime, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Prime', new_prime_path %>

trycf/app/views/primes/new.html.erb
<h1>New prime</h1>

<%= render 'form' %>

<%= link_to 'Back', primes_path %>

trycf/app/views/primes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Num:</b>
  <%= @prime.num %>
</p>

<p>
  <b>Is prime:</b>
  <%= @prime.is_prime %>
</p>


<%= link_to 'Edit', edit_prime_path(@prime) %> |
<%= link_to 'Back', primes_path %>